# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  mode: system
  color: blue

# SEO
marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: ''
    description: 'The highly-customizable Hugo Academic theme powered by Hugo Blox Builder. Easily create your personal academic website.'
    twitter: 'GetResearchDev'
  analytics:
    google_analytics: ''
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  verification:
    google: ''
    baidu: ''

# Site header
# header:
#   navbar:
#     enable: true
#     blox: "navbar"
#     fixed_to_top: true
#     show_search: true
#     show_theme_chooser: true
#     logo:
#       text: "Your Name"
header:
  navbar:
    # Display the navigation bar?
    enable: true
    # Choose a built-in navigation blox or create your own
    blox: "navbar"
    # Align menu links: `left`, `center`, or `right`
    align: "right"
    # Fix the navigation bar to the top of the page
    fixed_to_top: true
    # local text and icon on the left of the navigation bar
    # logo:
      # Logo text
      # text: "Your Name"
      # Logo filename in `assets/media/` folder
      # filename: "logo.svg"
    # Shop a call-to-action button in the top right?
    # button:
    #   enable: true
    #   text: "Get Started"
    #   url: "https://hugoblox.com/templates/"
    # Let the user choose between light or dark mode?
    show_theme_chooser: true
    # Let the user search from the navigation bar?
    show_search: false
    # Attempt to automatically highlight the active menu link? Can be disabled for complex sites.
    highlight_active_link: false
    # Show a language chooser (if you have translated your site content)?
    show_translations: false
    # If `show_translations` is enabled, do you wish to hide the current language name?
    hide_language_name: false

# Site footer
footer:
  copyright:
    notice: ''
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# Localization
locale:
  date_format: ''
  time_format: ''

# Site features
features:
  math:
    enable: false
  privacy_pack:
    enable: false
